# For more info on HTTP files go to https://aka.ms/vs/httpfile

POST http://localhost:11434/api/generate
Content-Type: application/json
{
  "model": "llama3.1",
  "prompt": "Décrit Microsoft en une phrase"
}


